extract:
#  Configuration for the extraction of treasury yield data
  treasury_yield:
#    List of maturity options
    options:
      - "3month"
      - "2year"
      - "5year"
      - "7year"
      - "10year"
#  Configuration for the extraction of exchange rate data
  exchange_rate:
#    List of exchange rate target currencies:
    currencies:
      - "EUR"
      - "JPY"
      - "RUB"
      - "AUD"
      - "GBP"
#  Configuration for the extraction of crypto price data
  crypto_price:
#    List of crypto symbols:
    symbols:
      - "BTC"
      - "ETH"
      - "DOGE"
    #markets:
    #  - "USD"
load:
  chunksize: 1000
transform:
  model_path: "fin_elt/models/transform"
meta:
  log_table: "pipeline_logs"